auth:
  - user: joppe
    group: joppe
    uid: 1000
    gid: 1000
    password_file: /data/joppe_password

global:
  - "force user = joppe"
  - "force group = joppe"

share:
  - name: share
    path: /samba/share
    browsable: yes
    readonly: no
    guestok: no
    validusers: joppe
    writelist: joppe
    veto: no
