version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8084:80/tcp
    environment:
      TZ: 'Europe/Amsterdam'
    volumes:
      - '${HOST_ROOT}/etc/pihole/:/etc/pihole/'
      - '${HOST_ROOT}/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - NVIDIA_VISIBLE_DEVICES=all
      # - JELLYFIN_PublishedServerUrl=192.168.2.1 #optional
    volumes:
      - ./runtimeGenerated/jellyfin/config:/config
      - ./runtimeGenerated/jellyfin/cache:/cache
      - ${HOME}/files/series:/data/series
      - ${HOME}/files/films:/data/films
      - ${HOME}/files/torrents/downloaded:/data/torrents
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [ gpu ]

  minecraft:
    container_name: minecraft
    restart: unless-stopped
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"
      TYPE: "FORGE"
      FORGEVERSION: "40.1.68"
    tty: true
    stdin_open: true
    volumes:
      - ./runtimeGenerated/minecraft:/data

  factorio:
    container_name: factorio
    image: goofball222/factorio:experimental
    restart: unless-stopped
    ports:
      - 27015:27015
      - 34197:34197/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtimeGenerated/factorio:/factorio
    environment:
      - TZ=Europe/Amsterdam

  rclone:
    container_name: rclone
    restart: unless-stopped
    build: ./rclone
    volumes:
      - ${HOME}/files/dump/googleDrive/:/googleDrive
      - ./runtimeGenerated/rclone/var/log/:/var/log/

  nextcloud-db:
    container_name: nextcloud-db
    restart: unless-stopped
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./runtimeGenerated/nextcloud-db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    restart: unless-stopped
    image: nextcloud
    links:
      - nextcloud-db
    volumes:
      - ./runtimeGenerated/nextcloud-app/var/www/html:/var/www/html
      - ${PWD}/nextcloud/config.php:/var/www/html/config/config.php
      - /home/joppe/files:/files
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

  cron:
    image: rcdailey/nextcloud-cronjob
    restart: unless-stopped
    network_mode: none
    depends_on:
      - nextcloud-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
      - NEXTCLOUD_PROJECT_NAME=server1
      - DEBUG=1
