version: "3"

services:
  nodejs:
    build: ./nodejs
    ports:
      - 8080:8080
    volumes:
      - './nodejs:/app'
    restart: unless-stopped

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=joppe.koers@gmail.com
      # - STAGING=1
      # - USE_ECDSA=1 # maybe in the future
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./runtimeGenerated/nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/joppekoers.nl.conf

  plex:
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5354:5353/udp # should be the same port, but on ubunutu ahavi-daemon uses the 5353 port already
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./runtimeGenerated/plex/config:/config
      - ${HOME}/files/series:/mnt/series
      - ${HOME}/files/films:/mnt/films
      - ${HOME}/files/torrents/downloaded:/mnt/torrents
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8081
    volumes:
      - ./runtimeGenerated/qbittorrent/config:/config
      - ${HOME}/files/torrents/:/mnt/files
    ports:
      - 8081:8081
    restart: unless-stopped

  hours:
    build: ./codamHours
    restart: unless-stopped
    volumes:
      - ./codamHours/database.json:/app/database.json
      - ./codamHours/env:/app/env
      - ./codamHours/sessions:/app/sessions

  # hours:
  #   build:
  #     context: ./codamHours
  #     dockerfile: Dockerfile.dev
  #   restart: unless-stopped
  #   volumes:
  #     - ./codamHours:/app

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - 53:53/tcp
  #     - 53:53/udp
  #     - 67:67/udp
  #     - 8084:80/tcp
  #   environment:
  #     TZ: 'Europe/Amsterdam'
  #   volumes:
  #     - '${HOST_ROOT}/etc/pihole/:/etc/pihole/'
  #     - '${HOST_ROOT}/etc/dnsmasq.d/:/etc/dnsmasq.d/'
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

  rclone:
    build: ./rclone
    volumes:
      - ${HOME}/files/dump/googleDrive/:/googleDrive
      - ./runtimeGenerated/rclone/var/log/:/var/log/
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - NVIDIA_VISIBLE_DEVICES=all
      # - JELLYFIN_PublishedServerUrl=192.168.2.1 #optional
    volumes:
      - ./runtimeGenerated/jellyfin/config:/config
      - ./runtimeGenerated/jellyfin/cache:/cache
      - ${HOME}/files/series:/data/series
      - ${HOME}/files/films:/data/films
      - ${HOME}/files/torrents/downloaded:/data/torrents
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - capabilities: [ gpu ]
