version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8084:80/tcp
    environment:
      TZ: 'Europe/Amsterdam'
    volumes:
      - '${HOST_ROOT}/etc/pihole/:/etc/pihole/'
      - '${HOST_ROOT}/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


  minecraft:
    container_name: minecraft
    restart: unless-stopped
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.3"
      MEMORY: 2G
    tty: true
    stdin_open: true
    volumes:
      - ./runtimeGenerated/minecraft:/data

  factorio:
    container_name: factorio
    restart: unless-stopped
    image: factoriotools/factorio
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtimeGenerated/factorio:/factorio
    environment:
      - TZ=Europe/Amsterdam

  rclone:
    container_name: rclone
    restart: unless-stopped
    build: ./rclone
    volumes:
      - ${HOME}/files/dump/googleDrive/:/googleDrive
      - ./runtimeGenerated/rclone/var/log/:/var/log/

  samba:
    image: crazymax/samba
    restart: unless-stopped
    volumes:
      - ./samba/config.yml:/data/config.yml
      - ./samba/password_joppe:/data/password_joppe:ro
      - /home/joppe:/samba/share
    ports:
      - 445:445
    environment:
      - TZ=Europe/Amsterdam
      - SAMBA_LOG_LEVEL=0

  nfs:
    container_name: nfs
    restart: unless-stopped
    image: erichough/nfs-server
    privileged: true
    volumes:
      - /home/joppe/files:/share
    environment:
      - NFS_EXPORT_0=/share *(rw,fsid=0,insecure,no_subtree_check,all_squash)
      # - NFS_EXPORT_0=/share joppe(rw,fsid=0,insecure,no_subtree_check,no_root_squash)
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    ports:
      - 111:111
      - 2049:2049
      - 32765:32765
      - 32767:32767
