version: "3"

services:
  nodejs:
    build: ./nodejs
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/

  certbot:
    image: certbot/certbot
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt/:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/
    command: certonly --email joppe.koers@gmail.com --agree-tos --no-eff-email --dry-run --staging -d joppekoers.nl -d www.joppekoers.nl -d torrents.joppekoers.nl -d plex.joppekoers.nl -d files.joppekoers.nl
