services:
  joppekoers.nl:
    container_name: joppekoers.nl
    image: ghcr.io/sirmorfield/joppekoers.nl/frontend
    restart: unless-stopped
    environment:
      - PORT=8080

  cms:
    container_name: cms
    image: ghcr.io/sirmorfield/joppekoers.nl/cms
    restart: unless-stopped
    volumes:
      - ./runtimeGenerated/cms/projects:/app/projects
      - ./runtimeGenerated/cms/media:/app/media
    environment:
      - PORT=1337
    ports:
      - 1337:1337

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_ROLLING_RESTART=true
    command: joppekoers.nl pixels cms github-runner-celebratix

  plex:
    container_name: plex
    restart: unless-stopped
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5354:5353/udp # should be the same port, but on ubunutu ahavi-daemon uses the 5353 port already
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./runtimeGenerated/plex/config:/config
      - ${HOME}/files/series:/mnt/series
      - ${HOME}/files/films:/mnt/films
      - ${HOME}/files/torrents/downloaded:/mnt/torrents

  # https://jellyfin.org/docs/general/installation/container
  jellyfin:
    container_name: jellyfin
    restart: unless-stopped
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    # user: uid:gid
    volumes:
      - ./runtimeGenerated/jellyfin/config:/config
      - ./runtimeGenerated/jellyfin/cache:/cache
      - ${HOME}/files/films:/files/films:ro
      - ${HOME}/files/series:/files/series:ro
      - ${HOME}/files/torrents/downloaded:/files/torrents:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.joppekoers.nl
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - host.docker.internal:host-gateway

  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8081
    volumes:
      - ./runtimeGenerated/qbittorrent/config:/config
      - ${HOME}/files/torrents/:/mnt/files

  syncthing:
    container_name: syncthing
    restart: unless-stopped
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./runtimeGenerated/syncthing/var/syncthing:/var/syncthing
      - /home/joppe/files/sync:/sync
      - /home/joppe/git:/git
      - /home/joppe/git_deleted:/git_deleted
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /home/joppe:/srv
      - ./runtimeGenerated/filebrowser/database.db:/database.db
      - ./runtimeGenerated/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 1111:80

  spacedrive:
    container_name: spacedrive
    image: ghcr.io/spacedriveapp/spacedrive/server
    ports:
      - 1112:8080
    env_file:
      - ./spacedrive/.env
    volumes:
      - ./runtimeGenerated/spacedrive/var/spacedrive:/var/spacedrive
      - /home/joppe/files:/files

  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env_file: ./datadog-agent/.env
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 10001:8125/udp

  pixels:
    container_name: pixels
    image: ghcr.io/pixelcorp-nl/canvas.edu/canvas.edu
    restart: unless-stopped
    env_file:
      - ./pixels/.env
    depends_on:
      - redis
      - postgres
    ports:
      - 5173:5173

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./runtimeGenerated/pixels/redis-db:/data

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./runtimeGenerated/pixels/postgres-db:/var/lib/postgresql/data

  github-runner-celebratix:
      container_name: github-runner-celebratix
      image: ghcr.io/celebratix/docker-github-actions-runner:ubuntu-latest
      restart: unless-stopped
        # deploy:
        #       mode: replicated
        # replicas: 2
      environment:
          - RUNNER_NAME_PREFIX=joppe-server1
          - RUNNER_WORKDIR=/runner
          - RUNNER_GROUP=joppe-group
          - RUNNER_SCOPE=org
          - ORG_NAME=Celebratix
          - LABELS=joppe
      env_file:
          - ./github-runner-celebratix/.env
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./runtimeGenerated/github-runner-celebratix/runner:/runner
          - ./runtimeGenerated/github-runner-celebratix/root/.nuget/packages:/root/.nuget/packages
          - ./runtimeGenerated/github-runner-celebratix/var/lib/docker/overlay2:/var/lib/docker/overlay2

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: always
    # ports:
    #   - 4343:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_ADDITIONAL_NETWORK=server1_default
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  factorio:
    container_name: factorio
    restart: unless-stopped
    image: factoriotools/factorio
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./runtimeGenerated/factorio:/factorio

  tunnel:
    container_name: tunnel
    depends_on:
      - nginx
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./tunnel/.env

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:alpine
    environment:
      - CERTBOT_EMAIL=joppe.koers@gmail.com
      # - STAGING=1
      # - USE_ECDSA=1 # maybe in the future
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      joppekoers.nl:
        condition: service_started
      cms:
        condition: service_started
      plex:
        condition: service_started
      qbittorrent:
        condition: service_started
      syncthing:
        condition: service_started
      filebrowser:
        condition: service_started
      jellyfin:
        condition: service_started
      # nextcloud-aio-mastercontainer:
      #   condition: service_started

volumes:
  nextcloud_aio_mastercontainer:
    external: true
    name: nextcloud_aio_mastercontainer
