version: '3'

services:
  nodejs:
    container_name: nodejs
    restart: unless-stopped
    build:
      context: ./nodejs
      target: frontend
    env:
      - PORT=8080

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: jonasal/nginx-certbot:latest
    environment:
      - CERTBOT_EMAIL=joppe.koers@gmail.com
      # - STAGING=1
      # - USE_ECDSA=1 # maybe in the future
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./runtimeGenerated/nginx/etc/letsencrypt:/etc/letsencrypt
      - ./runtimeGenerated/nginx/var/log/letsencrypt:/var/log/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/joppekoers.nl.conf

  plex:
    container_name: plex
    restart: unless-stopped
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5354:5353/udp # should be the same port, but on ubunutu ahavi-daemon uses the 5353 port already
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./runtimeGenerated/plex/config:/config
      - ${HOME}/files/series:/mnt/series
      - ${HOME}/files/films:/mnt/films
      - ${HOME}/files/torrents/downloaded:/mnt/torrents

  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8081
    volumes:
      - ./runtimeGenerated/qbittorrent/config:/config
      - ${HOME}/files/torrents/:/mnt/files

  rclone:
    container_name: rclone
    restart: unless-stopped
    build: ./rclone
    volumes:
      - ${HOME}/files/dump/googleDrive/:/googleDrive
      - ./runtimeGenerated/rclone/var/log/:/var/log/

  samba:
    container_name: samba
    restart: unless-stopped
    build: ./samba
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf
      - /home/joppe:/share
    ports:
      - 445:445

  backend:
    container_name: bookclub-voting-backend
    restart: unless-stopped
    build:
      context: ./bookclub-voting/backend
      target: production
    volumes:
      # - ./backend:/app/
      - backend_node_module:/app/node_modules
    env_file:
      - ./bookclub-voting/.env
    depends_on:
      - postgres

  frontend:
    container_name: bookclub-voting-frontend
    restart: unless-stopped
    build:
      context: ./bookclub-voting/frontend
      target: production
    volumes:
      - frontend_node_module:/app/node_modules
    env_file:
      - ./bookclub-voting/.env

  postgres:
    container_name: bookclub-voting-postgres
    restart: unless-stopped
    image: postgres:13
    env_file:
      - ./bookclub-voting/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextcloud-db:
    container_name: nextcloud-db
    restart: unless-stopped
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./runtimeGenerated/nextcloud-db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    container_name: nextcloud-app
    restart: unless-stopped
    image: nextcloud
    links:
      - nextcloud-db
    volumes:
      - ./runtimeGenerated/nextcloud-app/var/www/html:/var/www/html
      - ${PWD}/nextcloud/config.php:/var/www/html/config/config.php
      - /home/joppe/files:/files
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

  syncthing:
    container_name: syncthing
    restart: unless-stopped
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./runtimeGenerated/syncthing:/var/syncthing
      - /home/joppe/files/sync:/sync
      - /home/joppe/git:/git
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts

  monitor:
    container_name: monitor
    build: ./monitor

volumes:
  backend_node_module:
  frontend_node_module:
  pgdata:
