version: "3"

services:
  nodejs:
    build: ./nodejs
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/

  plex:
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5354:5353/udp" #should be the same port, but on ubunutu ahavi-daemon uses the 5353 port already
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    volumes:
      - ${HOME}/files/config/plex:/config
      - ${HOME}/files/series:/mnt/series
      - ${HOME}/files/films:/mnt/films
      - ${HOME}/files/torrents/downloaded:/mnt/torrents
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8081
    volumes:
      - ${HOME}/files/torrents/config:/config
      - ${HOME}/files/torrents/:/mnt/files
    ports:
      - "8081:8081"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt/:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/
    command: certonly --email joppe.koers@gmail.com --agree-tos --no-eff-email --dry-run --staging -d joppekoers.nl -d www.joppekoers.nl -d torrents.joppekoers.nl -d plex.joppekoers.nl -d files.joppekoers.nl
