version: "3"

services:
  nodejs:
    build: ./nodejs
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    build: ./nginx
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/

  plex:
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - "32400:32400"
    volumes:
      - ${HOME}/files/config:/config
      - ${HOME}/files/series:/tv
      - ${HOME}/files/films:/movies
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ${HOST_ROOT}/etc/letsencrypt/:/etc/letsencrypt
      - ${HOST_ROOT}/var/lib/letsencrypt/:/var/lib/letsencrypt/
    command: certonly --email joppe.koers@gmail.com --agree-tos --no-eff-email --dry-run --staging -d joppekoers.nl -d www.joppekoers.nl -d torrents.joppekoers.nl -d plex.joppekoers.nl -d files.joppekoers.nl
