version: '3'

services:
  joppekoers.nl:
    container_name: joppekoers.nl
    image: ghcr.io/sirmorfield/joppekoers.nl/frontend
    restart: unless-stopped
    volumes:
      - ./cdn.joppekoers.nl/projectImg:/app/build/client/img/projectImg
    environment:
      - PORT=8080

  cms:
    container_name: cms
    image: ghcr.io/sirmorfield/joppekoers.nl/cms
    restart: unless-stopped
    volumes:
      - ./cms/public/uploads:/app/public/uploads
      - ./cms/db.db:/app/db.db
    env_file:
      - cms/.env
    environment:
      - PORT=1337
    ports:
      - 1337:1337

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_ROLLING_RESTART=true
    command: joppekoers.nl pixels cms

  plex:
    container_name: plex
    restart: unless-stopped
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-Le_ex28z3gJAske8w7nZ
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5354:5353/udp # should be the same port, but on ubunutu ahavi-daemon uses the 5353 port already
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./runtimeGenerated/plex/config:/config
      - ${HOME}/files/series:/mnt/series
      - ${HOME}/files/films:/mnt/films
      - ${HOME}/files/torrents/downloaded:/mnt/torrents

  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8081
    volumes:
      - ./runtimeGenerated/qbittorrent/config:/config
      - ${HOME}/files/torrents/:/mnt/files

  syncthing:
    container_name: syncthing
    restart: unless-stopped
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./runtimeGenerated/syncthing/var/syncthing:/var/syncthing
      - /home/joppe/files/sync:/sync
      - /home/joppe/git:/git
      - /home/joppe/git_deleted:/git_deleted
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts

  filebrowser:
    container_name: filebrowser
    volumes:
      - /home/joppe:/srv
      - ./runtimeGenerated/filebrowser/database.db:/database.db
      - ./runtimeGenerated/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 8080:80
    image: filebrowser/filebrowser

  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env_file: .env
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 10001:8125/udp

  nfs:
    container_name: nfs
    restart: unless-stopped
    image: erichough/nfs-server
    privileged: true
    volumes:
      - /home/joppe/files:/share
    environment:
      - NFS_EXPORT_0=/share *(rw,fsid=0,insecure,no_subtree_check,all_squash)
      # - NFS_EXPORT_0=/share joppe(rw,fsid=0,insecure,no_subtree_check,no_root_squash)

    cap_add:
      - SYS_ADMIN
      - SETPCAP
    ports:
      - 111:111
      - 2049:2049
      - 32765:32765
      - 32767:32767

  pixels:
    container_name: pixels
    image: ghcr.io/pixelcorp-nl/canvas.edu/canvas.edu
    restart: unless-stopped
    env_file:
      - ./pixels/.env
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./runtimeGenerated/pixels/redis-db:/data

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./runtimeGenerated/pixels/postgres-db:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=joppe.koers@gmail.com
      # - STAGING=1
      # - USE_ECDSA=1 # maybe in the future
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./runtimeGenerated/nginx/etc/letsencrypt:/etc/letsencrypt
      - ./runtimeGenerated/nginx/var/log/letsencrypt:/var/log/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/joppekoers.nl.conf:ro
    depends_on:
      joppekoers.nl:
        condition: service_started
      cms:
        condition: service_started
      plex:
        condition: service_started
      qbittorrent:
        condition: service_started
      syncthing:
        condition: service_healthy
      filebrowser:
        condition: service_healthy
